pipeline {
    agent any

    stages {
        stage('Git') {
            steps {
                git url: 'https://github.com/Mahesh-Pradhan/Epam-Repo/tree/epam/CA-4.git', branch: 'main'
            }
        }
    stage('Deploy'){
           steps{
               sh 'ansible-playbook EC2-instances.yml'
           }
        }  
    }
}
