---
- name: start an instance with a public IP address
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create EC2
      amazon.aws.ec2_instance:
        name: "epam-exam-instance"
        region: us-east-1
        # key_name: "ansible_ssh_key"
        vpc_subnet_id: 
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-007855ac798b5175e
        state: present  # stopped
        tags:
          Environment: Testing
